### ISSUE TITLE
mainwindow.ui is missing!

### ISSUE THREAD

**Issue by alezz** [gmittone/FibonacciClock#1]

**Comment by gmittone** [comment]
mainwindow.ui is not requested nor required in this project

**Comment by alezz** [comment]
so why in mainwindow.cpp is there the following line?
`#include "ui_mainwindow.h"`

i needed to comment that line out and add the following to compile
`#include <QAction>`
`#include <QApplication>`

**Comment by alezz** [comment]
i needed to comment that line out and add the following to compile
#include <QAction>
#include <QApplication>

**Comment by gmittone** [comment]
The final commit was missing.
